name: FluxPerMillion
main: com.github.pietw3lve.fpm.FluxPerMillion
version: 1.1.0
api-version: 1.15
authors: ['PieTw3lve']
website: https://github.com/PieTw3lve/FluxPerMillion
description: Introduces a new game mechanic, Flux, which is a measure of the environmental impact of player actions.

commands:
  FluxPerMillion:
    usage: /fpm <help|inspect|lookup|reload|status|toggle>...
    aliases: [fluxpermillion]
    description: Universal command for the plugin. Use /fpm help, for more information.

# Dependencies
depend: []
# Soft Dependencies
softdepend: [DeadlyDisasters, PlaceholderAPI]
