# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Deadly Disasters library
        run: mvn install:install-file -Dfile=lib/DeadlyDisasters-V11.0.jar -DgroupId=com.github.pietw3lve -DartifactId=DeadlyDisasters -Dversion=11.0 -Dpackaging=jar
      - name: Build with Maven
        run: mvn -B package --file pom.xml
